### ISSUE TITLE
Text bug of form

### ISSUE THREAD

**Issue by fight-fly** [GaberildeGabrielo/GabrieloRomToolsGUI#2]
Hello, do you have any ideas about the text misalignment?

file crc32: 871eb9da
2024-04-03

![sshot-1](https://github.com/user-attachments/assets/af8dac0b-6e5a-4c26-aa37-0dabf2e060a7)

Btw, thank you for your program.

**Comment by gaberilde** [comment]
lookd like your computer is missing the standard font so the text is glitching out, sadly a issue with your pc setup more then anything it looks like

**Comment by gaberilde** [comment]
Yea it appears to be a problem with the windows installation not providing the correct font and making the text too big, for reference here is what it should look like from mine:
![image](https://github.com/user-attachments/assets/ff28223a-7287-4290-9c64-0dc0dcb91c69)

Are you using a lite edition of windows from online? they tend to remove stuff that can be important sometimes or are you using one from microsoft?
